name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    name: Test Julia ${{matrix.version}} - ${{matrix.os}} - ${{matrix.arch}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        version: ['1.5', nightly]
        os: [ubuntu-latest]
        arch: [x64]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{matrix.version}}
          arch: ${{matrix.arch}}
      - uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{secrets.BUILDBOT_SSH_KEY}}
      - run: julia --color=yes -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url = "git@github.com:GraystoneTechnologies/GraystoneRegistry.git"))'
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./lcov.info
          flags: unittest